### ISSUE TITLE
Doesn't work with updated Waffle

### ISSUE THREAD

**Issue by almirsarajcic** [kolorahl/waffle_gcs#4]
When I run `mix deps.get` I get the following error message:
```
Resolving Hex dependencies...

Failed to use "waffle" (version 1.1.0) because
  waffle_gcs (versions 0.1.0 and 0.1.1) requires ~> 0.0.3
  mix.exs specifies ~> 1.1.0

** (Mix) Hex dependency resolution failed, change the version requirements of your dependencies or unlock them (by using mix deps.update or mix deps.unlock). If you are unable to resolve the conflicts you can try overriding with {:dependency, "~> 1.0", override: true}
```

Needs an update for `waffle` from version 0.0.3 to 1.1.0.

**Comment by achempion** [comment]
There are should not be any breaking changes. We updated S3 configuration options with the new major update. Shouldn't affect GCS storage provider.

**Comment by pironim** [comment]
same issue you have wafle dependency version limit
https://github.com/kolorahl/waffle_gcs/blob/master/mix.exs#L40
